/**
 * Dummy Users for Standalone Mode Testing
 * 
 * Use these credentials to test login:
 * - Admin: admin@school.com / admin123
 * - Teacher: teacher@school.com / teacher123
 * - Student: student@school.com / student123
 */

import { User } from "@/types/auth";

export interface DummyUser extends User {
  password: string;
}

export const dummyUsers: DummyUser[] = [
  {
    _id: "user_admin_001",
    email: "admin@school.com",
    password: "admin123",
    firstName: "Admin",
    lastName: "User",
    role: "admin",
    status: true,
    phone: "9876543210",
  },
  {
    _id: "user_teacher_001",
    email: "teacher@school.com",
    password: "teacher123",
    firstName: "John",
    lastName: "Teacher",
    role: "teacher",
    status: true,
    phone: "9876543211",
  },
  {
    _id: "user_teacher_002",
    email: "mary@school.com",
    password: "mary123",
    firstName: "Mary",
    lastName: "Smith",
    role: "teacher",
    status: true,
    phone: "9876543212",
  },
  {
    _id: "user_student_001",
    email: "student@school.com",
    password: "student123",
    firstName: "Rahul",
    lastName: "Kumar",
    role: "student",
    status: true,
    phone: "9876543213",
  },
  {
    _id: "user_student_002",
    email: "priya@school.com",
    password: "priya123",
    firstName: "Priya",
    lastName: "Sharma",
    role: "student",
    status: true,
    phone: "9876543214",
  },
];

/**
 * Simulate login API call
 * Returns user data and token if credentials match
 */
export const authenticateUser = (
  email: string,
  password: string
): { success: boolean; message: string; data?: { user: User; token: string } } => {
  // Find user by email
  const user = dummyUsers.find(
    (u) => u.email.toLowerCase() === email.toLowerCase()
  );

  if (!user) {
    return {
      success: false,
      message: "User not found. Please check your email.",
    };
  }

  // Check password
  if (user.password !== password) {
    return {
      success: false,
      message: "Invalid password. Please try again.",
    };
  }

  // Check if user is active
  if (!user.status) {
    return {
      success: false,
      message: "Your account has been deactivated. Please contact admin.",
    };
  }

  // Generate dummy JWT token (in real app, this comes from backend)
  const token = generateDummyToken(user);

  // Remove password from user object
  const { password: _, ...userWithoutPassword } = user;

  return {
    success: true,
    message: "Login successful!",
    data: {
      user: userWithoutPassword,
      token,
    },
  };
};

/**
 * Generate a dummy JWT-like token for testing
 * In real app, this is generated by backend
 */
function generateDummyToken(user: DummyUser): string {
  // Create a simple base64 encoded token (NOT secure, only for testing)
  const header = btoa(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = btoa(
    JSON.stringify({
      id: user._id,
      email: user.email,
      role: user.role,
      firstName: user.firstName,
      lastName: user.lastName,
      iat: Math.floor(Date.now() / 1000),
      exp: Math.floor(Date.now() / 1000) + 24 * 60 * 60, // 24 hours
    })
  );
  const signature = btoa("dummy-signature-for-testing");

  return `${header}.${payload}.${signature}`;
}

/**
 * Get user by email (for testing)
 */
export const getUserByEmail = (email: string): User | undefined => {
  const user = dummyUsers.find(
    (u) => u.email.toLowerCase() === email.toLowerCase()
  );
  if (user) {
    const { password: _, ...userWithoutPassword } = user;
    return userWithoutPassword;
  }
  return undefined;
};

